version: '3.6'

services:
  monit:
    build:
      args:
        alpine_tag: ${ALPINE_TAG}
        monit_version: ${MONIT_VERSION}
      context: .
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
