#!/bin/bash

set -euo pipefail

function check_pid() {
  local -r pid=$(pidof monit)

  if [[ "${pid}" != "1" ]]; then
    exit 1
  fi
}

function check_port() {
  set +e
  curl -I 0.0.0.0:2812 &> /dev/null
  local result="$?"
  set -euo pipefail

  if [[ "${result}" != "0" ]]; then
    exit 1
  fi
}

function main() {
  check_pid
  check_port
}

main "$@"
